version: "3.3"

services:
  ms-auth:
    container_name: ms-auth
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-reservations.rule=PathPrefix(`/reservations`)"
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
    ports:
      - 7701:5000
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: 